sqlite:
  filename: fids_db3.db

scanas:
  image_path: /dev/nvme0n1p5
  scan_paths: 
    [
      "/",
      "/nonExisting",
    ]
  ignore_paths: 
    [
    ]
  validate_mode: true

  
investigator:
  same_config: True
  rules: 
    - name: php
      rules: 
        - m
        - i
        - l
        - n
        - a
      equal:
        - meta_creation_time
        - meta_size
    - name: logs
      greater:
        - meta_size
      equal:
        - meta_creation_time
      rules:
  investigations:
    - paths:
        - '/etc'
      fileregexwhitelist:
        - '*.php'
      rules:
        - php
    - fileregexwhitelist: '/*'
      fileregexblacklist: '*evilfile*'
      rules:
        - logs


