sqlite:
  filename: fids_db3.db

scanas:
  image_path: /dev/nvme0n1p5
  scan_paths: 
    [
      "/",
      "/nonExisting",
    ]
  ignore_paths: 
    [
    ]
  validate_mode: true

  
investigator:
  rules: 
    - name: php
      inlcuded: 
        - m
        - i
        - l
        - n
        - a
      equal:
        - meta_creation_time
        - meta_size
      regex: '*.php'
    - name: logs
      greater:
        - meta_size
      equal:
        - meta_creation_time
  investigations:
    - paths:
        - '/etc'
      filegroupregex:
        - '/etc/*.php'
        - '/var/www/html'
      rules:
        - php
    - filegroupregex:
        - '/*'
      rules:
        - logs


