sqlite:
  filename: fids_db3.db

scan:
  image_path: /dev/nvme0n1p5
  scan_paths: 
    [
      "/",
      "/nonExisting",
    ]
  ignore_paths: 
    [
    ]
  validate_mode: true

  
detectionas:
  filename_regex: ''
  greater: [
    meta_size
  ]
  equal: [
    meta_creation_time
  ]
  same_config: False