sqlite:
  filename: fids_db2.db

scan:
  image_path: ../images/usb1.dd
  scan_paths: 
    [
      "/",
      "/nonExisting",
    ]
  ignore_paths: 
    [
      
    ]
  validate_mode: true
detection:
  fixed_values: []
  compared: []