sqlite:
  filename: fids_db3.db

scanasd:
  image_path: /dev/disk2
  offset: 7168
  scan_paths: 
    [
      "/",
      "/nonExisting",
    ]
  ignore_paths: 
    [
    ]
  validate_mode: true

  
investigator:
  same_config: True
  rules: 
    - name: newfile
      rules: 
        - m
        - i
        - l
        - 'n'
        - a
      equal:
        - meta_creation_time
        - meta_size
  investigations:
    - paths:
        - '/'
      rules:
        - newfile
    - fileregexwhitelist: '.exe$'
      fileregexblacklist: '.exe$'


