db:
  host: localhost
  port: 5702
  dbname: fids
  user: root
  password: pw

fids:
  image_path: /dev/nvme0n1p5
  scan_paths: 
    [
      "/",
      "/nonExisting",
    ]
  ignore_paths: 
    [
      
    ]
  validate_mode: true
