sqlite:
  filename: fids_db_testing.db

scanas:
  image_path: /dev/nvme0n1p5
  scan_paths: 
    [
      "/home/julian/fids/",
      "/nonExisting",
    ]
  ignore_paths: 
    [
      "/home/julian/fids/.git/",
    ]
  validate_mode: true

  
detection:
  filename_regex: ''
  greater: [
    meta_size
  ]
  equal: [
    meta_creation_time
  ]
  same_config: False